# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name medusa-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .MEDUSA_JWT_SECRET }}"
        COOKIE_SECRET: "{{ .MEDUSA_COOKIE_SECRET }}"
        STORE_CORS: "https://storefront.${SECRET_DOMAIN}"
        ADMIN_CORS: "https://medusa.${SECRET_DOMAIN}"
        AUTH_CORS: "https://medusa.${SECRET_DOMAIN},https://storefront.${SECRET_DOMAIN}"
        MEDUSA_BACKEND_URL: "https://medusa.${SECRET_DOMAIN}"
  dataFrom:
    - extract:
        key: medusa
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name medusa-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        DATABASE_URL: 'postgres://{{ .user }}:{{ .password }}@{{ index . "pgbouncer-host" }}:5432/{{ .dbname }}?uselibpqcompat=true&sslmode=require'
        POSTGRES_USER: '{{ .user }}'
        POSTGRES_PASSWORD: '{{ .password }}'
        POSTGRES_DB: '{{ .dbname }}'
        POSTGRES_HOST: '{{ index . "pgbouncer-host" }}'
        REDIS_URL: 'redis://dragonfly-master.database.svc.cluster.local:6379'
  dataFrom:
    - extract:
        key: postgres-pguser-medusa
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name medusa-s3-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        S3_ENDPOINT: "http://minio.storage.svc.cluster.local:9000"
        S3_BUCKET: "medusa-uploads"
        S3_REGION: "us-east-1"
        S3_FILE_URL: "https://s3.${SECRET_DOMAIN}/medusa-uploads"
        NEXT_PUBLIC_S3_FILE_URL: "https://s3.${SECRET_DOMAIN}/medusa-uploads"
        S3_ACCESS_KEY_ID: "{{ .MEDUSA_S3_ACCESS_KEY_ID }}"
        S3_SECRET_ACCESS_KEY: "{{ .MEDUSA_S3_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: medusa
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name storefront-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY: "{{ .MEDUSA_PUBLISHABLE_KEY }}"
        REVALIDATE_SECRET: "{{ .MEDUSA_REVALIDATE_SECRET }}"
  dataFrom:
    - extract:
        key: medusa
