---
apiVersion: v1
kind: Service
metadata:
  name: rybbit-backend
  namespace: development
spec:
  selector:
    app.kubernetes.io/name: rybbit-backend
  ports:
    - name: http
      port: 3001
      targetPort: http
