---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  SOPS_CONFIG_FILE: "{{.ROOT_DIR}}/.sops.yaml"

tasks:

  age-keygen:
    desc: Initialize Age Key for Sops
    cmd: age-keygen --output {{.AGE_FILE}}
    status:
      - test -f "{{.AGE_FILE}}"

  encrypt:
    desc: Encrypt all Kubernetes SOPS secrets that are not already encrypted
    cmds:
      - for: { var: file }
        task: .encrypt-file
        vars:
          file: "{{.ITEM}}"
    vars:
      file:
        sh: |
          if [ -d "{{.KUBERNETES_DIR}}" ]; then
              find "{{.KUBERNETES_DIR}}" -type f -name "*.sops.*" -exec grep -L "ENC\[AES256_GCM" {} \;
          fi

  .encrypt-file:
    internal: true
    cmd: sops --encrypt --in-place {{.file}}
    requires:
      vars: ["file"]
    preconditions:
      - { msg: "Missing Sops config file", sh: "test -f {{.SOPS_CONFIG_FILE}}" }
      - { msg: "Missing Sops Age key file", sh: "test -f {{.AGE_FILE}}" }

  .reset:
    internal: true
    cmd: rm -rf {{.SOPS_CONFIG_FILE}}

  push-age-key:
    desc: Push SOPS age key to Bitwarden Secrets Manager
    cmds:
      - bws secret edit 4a5e0a7a-c0a1-4e0f-9b0c-b1610100a9e8 --value "$(cat {{.AGE_FILE}})"
    preconditions:
      - { msg: "Missing Sops Age key file", sh: "test -f {{.AGE_FILE}}" }
      - { msg: "Bitwarden Secret Manager CLI not found", sh: "command -v bws" }
      - { msg: "BWS_ACCESS_TOKEN not set", sh: "test -n \"${BWS_ACCESS_TOKEN:-}\"" }

  pull-age-key:
    desc: Pull SOPS age key from Bitwarden Secrets Manager
    cmds:
      - mkdir -p $(dirname {{.AGE_FILE}})
      - bws secret get 4a5e0a7a-c0a1-4e0f-9b0c-b1610100a9e8 | jq -r '.value' > {{.AGE_FILE}}
      - chmod 600 {{.AGE_FILE}}
    preconditions:
      - { msg: "Bitwarden Secret Manager CLI not found", sh: "command -v bws" }
      - { msg: "JQ not found", sh: "command -v jq" }
      - { msg: "BWS_ACCESS_TOKEN not set", sh: "test -n \"${BWS_ACCESS_TOKEN:-}\"" }
