---
apiVersion: v1
kind: Service
metadata:
  name: minio-s3-lan
  namespace: storage
  annotations:
    external-dns.alpha.kubernetes.io/hostname: s3-lan.${SECRET_DOMAIN}
    io.cilium/lb-ipam-ips: "192.168.50.190"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/controller: minio
