---
apiVersion: batch/v1
kind: Job
metadata:
  name: "wipe-${app}-${ts}"
  namespace: "${ns}"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: wipe
          image: docker.io/library/busybox:latest@sha256:fd7dc98638c8e305f4dc34e979f1c0fdfdcaeb0fbf8fcff77ae834b6da3d7e6e
          command: ["/bin/sh", "-c", "cd /config; find . -delete"]
          volumeMounts:
            - name: config
              mountPath: /config
          securityContext:
            privileged: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: "${claim}"
