---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./cms
  - ../../../../templates/volsync
patches:
  - patch: |-
      - op: add
        path: /spec/restic/exclude
        value:
          - node_modules
          - .cache
          - .tmp
          - build
          - .strapi
    target:
      kind: ReplicationSource
