---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name bandit-demo-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        MLFLOW_TRACKING_URI: "{{ .mlflow_tracking_uri }}"
        MLFLOW_TRACKING_USERNAME: "{{ .mlflow_username }}"
        MLFLOW_TRACKING_PASSWORD: "{{ .mlflow_password }}"
        AWS_ACCESS_KEY_ID: "{{ .minio_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .minio_secret_key }}"
        MLFLOW_S3_ENDPOINT_URL: "{{ .minio_endpoint }}"
  dataFrom:
    - extract:
        key: bandit-demo
