---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name harbor-pull
spec:
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"harbor.${SECRET_DOMAIN}":{"username":"{{ .harbor_user }}","password":"{{ .harbor_password }}"}}}
  data:
    - secretKey: harbor_user
      remoteRef:
        key: bandit-demo
        property: harbor_user
    - secretKey: harbor_password
      remoteRef:
        key: bandit-demo
        property: harbor_password
