---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name bandit-demo-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        MLFLOW_TRACKING_URI: "http://mlflow.datasci.svc.cluster.local:5000"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        MLFLOW_S3_ENDPOINT_URL: "http://minio.storage.svc.cluster.local:9000"
  dataFrom:
    - extract:
        key: minio-secondary-creds
