---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: epsilon-greedy
  labels:
    app.kubernetes.io/name: bandit-demo
    app.kubernetes.io/component: seldon-model
spec:
  storageUri: "s3://bandit-models/epsilon_greedy/"
  server: bandit-mlserver
  requirements:
    - mlserver
  memory: 256Mi
---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: ucb
  labels:
    app.kubernetes.io/name: bandit-demo
    app.kubernetes.io/component: seldon-model
spec:
  storageUri: "s3://bandit-models/ucb/"
  server: bandit-mlserver
  requirements:
    - mlserver
  memory: 256Mi
---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: thompson-sampling
  labels:
    app.kubernetes.io/name: bandit-demo
    app.kubernetes.io/component: seldon-model
spec:
  storageUri: "s3://bandit-models/thompson_sampling/"
  server: bandit-mlserver
  requirements:
    - mlserver
  memory: 256Mi
---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: linucb
  labels:
    app.kubernetes.io/name: bandit-demo
    app.kubernetes.io/component: seldon-model
spec:
  storageUri: "s3://bandit-models/linucb/"
  server: bandit-mlserver
  requirements:
    - mlserver
  memory: 256Mi
---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: bayesian-ucb
  labels:
    app.kubernetes.io/name: bandit-demo
    app.kubernetes.io/component: seldon-model
spec:
  storageUri: "s3://bandit-models/bayesian_ucb/"
  server: bandit-mlserver
  requirements:
    - mlserver
  memory: 256Mi
---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: exp3
  labels:
    app.kubernetes.io/name: bandit-demo
    app.kubernetes.io/component: seldon-model
spec:
  storageUri: "s3://bandit-models/exp3/"
  server: bandit-mlserver
  requirements:
    - mlserver
  memory: 256Mi
---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: lints
  labels:
    app.kubernetes.io/name: bandit-demo
    app.kubernetes.io/component: seldon-model
spec:
  storageUri: "s3://bandit-models/lints/"
  server: bandit-mlserver
  requirements:
    - mlserver
  memory: 512Mi
