---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app filebrowser
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      filebrowser:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: filebrowser/filebrowser
              tag: v2.63.3@sha256:289c5dd677c56662440f26eeb44266ed9746fe563d2e9100f546bff558534d70
            env:
              TZ: ${TIMEZONE}
              FB_LOG: stdout
              FB_ROOT: /media
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        hosts:
          - host: &host filebrowser.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      data:
        existingClaim: filebrowser-data
        globalMounts:
          - path: /media
      config:
        existingClaim: filebrowser
        advancedMounts:
          filebrowser:
            app:
              - path: /database
                subPath: database
              - path: /config
                subPath: config
