---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: talos-worker3
  annotations:
    upgrade.cattle.io/force: "true"
spec:
  version: ${TALOS_VERSION}
  serviceAccountName: system-upgrade
  secrets:
    - name: talos
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  concurrency: 1
  exclusive: true
  nodeSelector:
    matchExpressions:
      - key: feature.node.kubernetes.io/system-os_release.ID
        operator: In
        values: ["talos"]
      - key: kubernetes.io/hostname
        operator: In
        values: ["worker3"]
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  prepare: &prepare
    image: ghcr.io/siderolabs/talosctl:${TALOS_VERSION}
    envs:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    args:
      - --nodes=$(NODE_IP)
      - health
      - --server=false
      - --wait-timeout=10m
  upgrade:
    <<: *prepare
    args:
      - --nodes=$(NODE_IP)
      - upgrade
      - --image=factory.talos.dev/metal-installer/${TALOS_SCHEMATIC_WORKER3}:${TALOS_VERSION}
      - --preserve
      - --reboot-mode=powercycle
