overlays:
  4K:
    overlay:
      name: 4K
      url: https://raw.githubusercontent.com/Kometa-Team/Kometa/master/config/overlays/4K.png
      horizontal_offset: 0
      horizontal_align: center
      vertical_offset: 0
      vertical_align: bottom
    plex_search:
      all:
        resolution: 4K
  HDR:
    overlay:
      name: HDR
      url: https://raw.githubusercontent.com/Kometa-Team/Kometa/master/config/overlays/HDR.png
      horizontal_offset: 0
      horizontal_align: center
      vertical_offset: 0
      vertical_align: bottom
    plex_search:
      all:
        hdr: true
