---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vllm
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-tools
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      vllm:
        replicas: 0
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: intel/vllm
              tag: 0.14.1-xpu@sha256:6aeeaba11a27dfb57da6448676f5eec23117823c6eae4a1c82978e8693b5a9c3
            args:
              - --host
              - "0.0.0.0"
              - --port
              - "8000"
              - --tensor-parallel-size
              - "1"
              - --dtype
              - half
              - --max-model-len
              - "4096"
              - --enforce-eager
            securityContext:
              privileged: true
            env:
              VLLM_OPENVINO_DEVICE: GPU
              VLLM_TARGET_DEVICE: xpu
              HF_HOME: /models
            resources:
              requests:
                cpu: 4
                memory: 8Gi
              limits:
                cpu: 8
                memory: 32Gi
                gpu.intel.com/i915: 1
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: kubernetes.io/hostname
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - *app
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8000
    persistence:
      models:
        existingClaim: vllm-models
        globalMounts:
          - path: /models
      dri:
        type: hostPath
        hostPath: /dev/dri
