---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app banditweb
spec:
  chart:
    spec:
      chart: app-template
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: harbor-pull
    controllers:
      banditweb:
        containers:
          app:
            image:
              repository: harbor.${SECRET_DOMAIN}/banditweb/bandit-frontend
              tag: latest
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 3000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 3
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 128Mi
      analysis:
        containers:
          app:
            image:
              repository: harbor.${SECRET_DOMAIN}/banditweb/bandit-analysis
              tag: latest
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
      analysis:
        controller: analysis
        ports:
          http:
            port: 8090
    ingress:
      app:
        className: internal
        hosts:
          - host: bandit.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - bandit.${SECRET_DOMAIN}
