---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banditweb-api
  namespace: datasci
spec:
  ingressClassName: internal
  rules:
    - host: bandit.${SECRET_DOMAIN}
      http:
        paths:
          - path: /bandit/
            pathType: Prefix
            backend:
              service:
                name: seldon-mesh
                port:
                  number: 80
  tls:
    - hosts:
        - bandit.${SECRET_DOMAIN}
