---
# yaml-language-server: $schema=https://kubernetes-schemas.minuette.horse/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: courier
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.6
  # bjw-s common library chart, so values have the app-template shape.
  url: oci://ghcr.io/misospace/charts/courier
