apiVersion: v1
kind: Secret
metadata:
    name: marimo-token
stringData:
    #ENC[AES256_GCM,data:ZsMYFR7fXa/hZGvM6gAX/zk2Hi96uYPDgvwf+gxAwIArNHVkKMKXCHMWP7F0lpbttEpVVGE=,iv:rvTIoaaGf/CER3D36KSorRgZiUpy10P2xLvNafsprIU=,tag:WIhaTd0U10viKaEAjuGW+w==,type:comment]
    #ENC[AES256_GCM,data:HpUthclG28WH8I8ykqU6ToMfvwTD6BG+TkmRvTZjvMo7kGdh2DZwEALOfItXRRlhpqUNOKyNCswvcwMKCmAtZkz/vrXK4paK,iv:jkmQRsnYV9bumeP5OUiGE2DXd7mLhbb9c+R7aRx0K64=,tag:8pte3lm0pAvfre/VbD4AQQ==,type:comment]
    #ENC[AES256_GCM,data:z7r0c3D0mF+M6SN618ikdkSQ/VVhjdpuzop1qjUAIPVewAfAb6sv3H3MCeZlF4qPRJg7SeSr3om7bxb+BEHVgktNnbhj1iQQlg==,iv:dNfSx4rXNC7seMu1EoAKop2evF2zJOaVHcx8f2iE44c=,tag:3nz7ZMA+PkgYvm5YlDx3vw==,type:comment]
    #ENC[AES256_GCM,data:xwYJpGEYVgjouG9ntSK4huLVGE+cGOjUqc7+aEHeqH8ID+g028tl5/i2vQtAKYFKw4zE,iv:Sd/3TAYqLovBkeEg2i1lQWKaGVXblvsGbNR4g4wz8zY=,tag:5u2v608wXHrl/iw6QI7bHw==,type:comment]
    token: ENC[AES256_GCM,data:JvpH+izX5vCB6frXgYvc77TIBAophKjEDLtACCx3MUc4BGmGQ7qONRf9jQ==,iv:ae9vGwwndOFMifh5YstczKiT6f0G65b1EDC5WExZN1Q=,tag:UuVPF0//yVS0ZRKe+Jahsw==,type:str]
sops:
    age:
        - recipient: age15wktkwh8dgasswz9u04axxaa4edc88nld3ajldnr3mtgjfmfyqtqc0cu0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoK1dDVkQ1aG5jempoNXA4
            QTBReWtOT0dlSlVtaW5aMW4wVlhCVy9WeHlFCkpLcHZMZEE2MndEUlRNekJVbGVN
            NmQ5RUNsUXBTU0I0R2MvOFB1TUREdTQKLS0tIERHQXFSTXNsZFZwTUlJemJXUGFZ
            encxd09tYUhYaXhaVk9YaVIxbmVHWjAKu1+SdOUWMT0G+EL5rUWyZcT7OG3Ab2x0
            tm0O4QBE5p2IbaQg9syfZCO7iZRM2SBK4AOyw+m8J3b3N6Z/M9klyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T08:36:26Z"
    mac: ENC[AES256_GCM,data:+hH/DqAFywW3LI6IhNiAWGKuWmg78B1kmSUrvyOMU2iBnJ4sSmPYA7nRDOJcJso/UkHp6uzJ8BsFuTczByODY8FxufYQ7ikArNwfLbYsK1MCZ6H7OREyQljULrNQ75nZwMkus958PMlXAw9IyNOnqZNkdeve+S2avBNzTvAEWRE=,iv:BGh0bxbLnQlCU0JHE+0EWVeOZqjHAXq4riLgk/LDRkA=,tag:PLmfRqK5pYm9kN4EbCKS7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
