apiVersion: v1
kind: Secret
metadata:
    name: marimo-token
stringData:
    #ENC[AES256_GCM,data:WFR6m2PK+goDCvE9ir6zeRDueQGmDyBK15jKGfYCIGFCFp7wCDDhao3WTIzrRIyya+vh+ZQ=,iv:vsCMiSvzn6ABWd4wpWGcsPa3MTE7k020zteaxTRbDp4=,tag:AX1Qo9570CDfpSAgLXTmcw==,type:comment]
    #ENC[AES256_GCM,data:Gw+V2c0if8NdnqW8PQ4j0CtsnaJi/HmCMmrUXGbHMB5fhrDH3eS9iW4lxDe7klfsfSD+aCIvyX4kmuj3hd71+0xzlD83gl/B,iv:uLw5J28bDSqcHoM/TR0oPQNBFxg8D8NBS2xNvPgnbeo=,tag:ksGQDWKKr4zX63NCP2SB/w==,type:comment]
    #ENC[AES256_GCM,data:2w7+J0hC5dx6BzZQTcBMxMvxPaTfddyX78nuxFNs356EBlX9hlAXy/h6odnlNEmxEADnkCTWnxsbz7vze+XeEIhzHDbdgun7Dg==,iv:HgbA+HHqQNnKLlVcw6l4SOZX4j0iZDwL4ItWcmiVSks=,tag:hfiZNbhSXTACrO6b74Bdcw==,type:comment]
    #ENC[AES256_GCM,data:XgNzmfSZGQDdY+YqqZcrGH6pR+nPCLbTqOQBHofanCUILCteysOkjIAYvwLllLWOUxMC,iv:4c9oprzBCeTE3pVlYKPG9fO/qFb8ZAvwegdbkBNxQgU=,tag:X6XggJfSKwO2y+GFRRt54Q==,type:comment]
    token: ENC[AES256_GCM,data:fLTyBuf+4JBxuJ57CZNg7/bqDqQE85I4jN+7pLf2sMgSs5hsvZfEcmG/Gw==,iv:RgQ7gvIodcKuev3BMuTcYLrKtOaRzbyIlWg5NOffQjQ=,tag:HLksiTxHdT19TSFB4bwYXA==,type:str]
sops:
    age:
        - recipient: age15wktkwh8dgasswz9u04axxaa4edc88nld3ajldnr3mtgjfmfyqtqc0cu0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZnBlellZanRVRW8yTkp6
            VHB0QTE5WDBRaFpJUGJrUktOQTZOL3hiM2o4CkhNUlFWUWtoY1FDZmZCVWh3VVBq
            SFNuWUkxSnZQRlBkbzJhODlmeXVOMTAKLS0tICtaR25TU2RBQkJ2V29uQndXL1ky
            UFkvVHBwK253bFpWT3RNVFZYYjFIbzgKYpNp89bvqtd5OM6kbKDty0LH2cmGnbFG
            iPB/pFlo8LWSTdp+qWupGNp1t7/+IKs72NYGAD+RL8h1DBSRfp1fOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T16:27:03Z"
    mac: ENC[AES256_GCM,data:XhDmo0RpWrS4AIeydJc/XdJZMN49FH/aSn3AvwSURoi8NzvU4HKtba0OFxfJzhlUYdwFRt64lehjWNdrl8r5MVjGxIePVO52q6w1/ZQ3KjASiGoJ/nG8XRN/cx+BRrKOCIBlKOeieNzTk/0UuLwFe0f1ovHgcA7qAn2IrJqfkQ8=,iv:4rknJkrWcVTjrMLEms4aehrTP/qQQvZewXZMg0XqN3Y=,tag:sozesstXq0EX2m6DJ/E/nA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: marimo-litellm
stringData:
    #ENC[AES256_GCM,data:p7kd86+L1lX/6OP06IUvp7jtBn/DYufqBtkKVO89gKXZhSsAR0z6L4dWTXj2q/OlM35SsE24NLKoDQ==,iv:/Awz4lksgn0vyPKAdDyhkRv4Iw+Q0GZwZ9ebiGOSGaA=,tag:Mk71MMA3tao9hJXLyNS9Dg==,type:comment]
    #ENC[AES256_GCM,data:P3S5BxOSNlx3Ul4bC6ZwntF5n4G019tYrslfTyRXXJNZCczeoyXkkgWnGfXLACBc8deYIT2SZPlmfevByFBCFfdynSwXAvCo,iv:vWqbJBc/0K+a8TYRwP2sHCR648TMaCrOgVNZO0BB8L4=,tag:x80bNqq2c1/8sNX9Hd7FMA==,type:comment]
    #ENC[AES256_GCM,data:YS+PKnLbrA47JCoXsJZ4cIkol/wtG4KBj9zgrhDJ7vwzCKAm28QIzMxzoQ==,iv:bwfRc4YMKzNfq6jU98gD4XvjNqEMm/De9W4QBv2kXjI=,tag:LpMRfDOqNGAdBojDvMeodQ==,type:comment]
    #
    #ENC[AES256_GCM,data:YVHhiU+v2KAQE9TmzoXVAdUoLpP7cgrLkCVj7S6w9TuEi63C4w5CIUS6HSWDHgWJmxOAfJ1N6cfEl9eTCWrUbI6KbyxMndCf2wg=,iv:qZn7m6gaSML9l3i0lJypaBEcL7k/X3gKGKMCh02GQGE=,tag:dG9QqdmhKdBMdA5TAwvNKA==,type:comment]
    #ENC[AES256_GCM,data:izbD6Oo52gANsGa25QbwRT5p0WK1AffXWGaBtI+BfCn/3nOKSjMajA9ga+KcITNbUUdScXcDudpWQH5GrF1jf9Hp1nGFptA=,iv:L8Ys0aJE2TwJ6gu7XUGTUl8am7M5eNj4FeKoVyVUIOw=,tag:BgkllppU8j1EATKmDACwkw==,type:comment]
    #ENC[AES256_GCM,data:dkIdlQOPzvSDidq2y4aMCJ68bwsKdEl8QN8wr4zzaUZLeUm5yhNgyOYI/LpnW2zCKqoKDJS03ank1lBrIzySCZCh/b5Er8A=,iv:ZbK1jKOuaPKCt9zLbXHt3Ghn13e9pzGzlF6+nURM87c=,tag:nNwxA47SH/fhu58QtvcstA==,type:comment]
    #ENC[AES256_GCM,data:B7s41T+TyrrmmhDsSzoGnsk78XjIdfbManU204a34uZulRNiujYS141bbdqVmW4rZJiEosHsLPac8VQb1AM3d+r9XMVqR4vk,iv:Zkb0/FHPnCPwdt1V4sxUy2jUVzKxfEVuXzBZgYabf8Y=,tag:4vT0tByzfwI0qN6CG87JyA==,type:comment]
    #ENC[AES256_GCM,data:hSEcmYhBGHUMfDCEcgeExoIA6uTAPuoFjC9Gj6Y1DFPG5jQHOZpWCuOba03JEg2AMXIVOtkx/W6hAgvncLIAmZCDhRo=,iv:WBiG0Fyhe2HbjZMQaftESg0jlNOHAKjYRC9y9bUO2Pk=,tag:/CzYdVZ4CX079B7avg9zSg==,type:comment]
    #ENC[AES256_GCM,data:itbrQBxIBgI=,iv:TkxmlctCiVYIG3+ISrXmSNrmUU6Lfg5wSyxqDLQjo2I=,tag:2kwTetXn0/u4Tmhy7XiT2g==,type:comment]
    #
    #ENC[AES256_GCM,data:Lb2HlJdtjIsXO23wJ2iA2EfXLHlT+EB1x3BQlFyfCsdNlZ5FHxOArzK73lzEjRFSifBH4FgNGnq3vNwcWP3sArECSTim,iv:+5Aw5DUmVaP4/gJ384lE5C102eez6xaed/bqIjnrsns=,tag:1+j6084Ik7y6wkbLSS8sZw==,type:comment]
    #ENC[AES256_GCM,data:0+p8YbKUXp8KtqDWPT7H7BgDqfUXNaSEk44RnPeci+8FVjU4qWxZ9MCdHKyumX110/8xjr6aUKFj+mOtVwIT6bI+VPk5X4Q=,iv:0dzmiQAW9ATW/Vr91vsRbdZKmKcmdMta9E6EohIn3zA=,tag:fm6OsGcHlQZrvR42gPe0oA==,type:comment]
    #ENC[AES256_GCM,data:QrNVBqyVtbb1utccM7Ytdfw=,iv:/kl/7bzGFz2yGM8Iu2+Fx4SUynsjeyUPCdxa15B0+9o=,tag:/psfwLROYpWx8+p9S1Dv1Q==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:3nz6eZ87Pyo0tvVUjTINeDElFhz/xYe4Xg==,iv:ZHLT2LIcZIjEtDW7y9WcYTEjef0AfH0NL42UfbCmk3w=,tag:vUIFSAMQZQBGAV0QYCQ2Qw==,type:str]
sops:
    age:
        - recipient: age15wktkwh8dgasswz9u04axxaa4edc88nld3ajldnr3mtgjfmfyqtqc0cu0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZnBlellZanRVRW8yTkp6
            VHB0QTE5WDBRaFpJUGJrUktOQTZOL3hiM2o4CkhNUlFWUWtoY1FDZmZCVWh3VVBq
            SFNuWUkxSnZQRlBkbzJhODlmeXVOMTAKLS0tICtaR25TU2RBQkJ2V29uQndXL1ky
            UFkvVHBwK253bFpWT3RNVFZYYjFIbzgKYpNp89bvqtd5OM6kbKDty0LH2cmGnbFG
            iPB/pFlo8LWSTdp+qWupGNp1t7/+IKs72NYGAD+RL8h1DBSRfp1fOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T16:27:03Z"
    mac: ENC[AES256_GCM,data:XhDmo0RpWrS4AIeydJc/XdJZMN49FH/aSn3AvwSURoi8NzvU4HKtba0OFxfJzhlUYdwFRt64lehjWNdrl8r5MVjGxIePVO52q6w1/ZQ3KjASiGoJ/nG8XRN/cx+BRrKOCIBlKOeieNzTk/0UuLwFe0f1ovHgcA7qAn2IrJqfkQ8=,iv:4rknJkrWcVTjrMLEms4aehrTP/qQQvZewXZMg0XqN3Y=,tag:sozesstXq0EX2m6DJ/E/nA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
