apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:R7yWpusynCJ73gN9PoKhz5jY,iv:BdD1yEOmihNVCe+cHSRMyOn8ROskNGbC2EgOr6WFr54=,tag:T/G3LfYdafCupqpzlgE7ww==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:+PTKLizCEic+ZYwToJ0yelbQ/AOAQ+7XZFsZSepJKdKB2pq/,iv:FkIDlbfBMnw8dI98oTK5wyRDG/soIdWjMjrG34YtPsE=,tag:humJjBzVBnOcMLg8n8D88g==,type:str]
    CLUSTER_SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:gGIVkJr+KpLuvwx91Ao3chGiLRu+THvWxVQwaEJfv9c=,iv:OW6QjtBxF0p4hWmT+YKKO5yfOPut4Dsto/0m39Xjw9U=,tag:+vDA3Yd2EgDyK7e0nDtcEw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Xh9Ud840VaSNUy4=,iv:bttYb1JhL+MXEIwtbF9UdS+F/7tmcvNjGH5HIze0m8g=,tag:uN446wt4GfgCR9dwpQgwmw==,type:str]
    SECRET_SECONDARY_DOMAIN: ENC[AES256_GCM,data:NiyCmn1L1N5pIKaNssM=,iv:DLhKuPahK2IO+1k8tCQFpSQCnrGCKtATv+jBouwE+t0=,tag:4nVH2PXo4m/9ofq+3B2iVA==,type:str]
    K8S_GW: ENC[AES256_GCM,data:Uznz+nZ+XVIun/DT8Gk=,iv:UD/6EDl+1McV0JDXC/zLyuTm06UvREQ3qa14VMPK1Ak=,tag:2r6eCK439S6t3CHbDk740Q==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:fHFWnUwveTZzhEMygwJEHJ/Qvpi1,iv:T+FE3UL49vSu1vc+nwNfnKMygHebF++dYUwSH0tlFUA=,tag:NnXDJGbdTy+bbKv1HuWQoA==,type:str]
    SVC_HOME_ASSISTANT_ADDR: ENC[AES256_GCM,data:Ozwh0WrTC/lUDm3VssE=,iv:E/8q83PYPyQi2/weKTWkmUXWuYH8SUTXJJChELMNsBM=,tag:/9SN7Mp7odNSwj1YnL4snA==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:C7zRnYHzYQ1cwt435rA=,iv:dHKvGiJDTxDajlPjQFu9hnFEUgxtQl+UPPCtZifQZF4=,tag:DwpSKROcmv7UJdCrs6QkEw==,type:str]
    SVC_SYNCTHING_ADDR: ENC[AES256_GCM,data:Ln5hPojYLLKDKhowaMY=,iv:PA9rQon00cg58v9dZetDDFkXbybmtcqAVsn1eFaOw+8=,tag:aqfKYPBuHgMQsrUbPmJFwQ==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:K3heslJJDjUsHicjw6o=,iv:SESR8CyAa/4a4jow15KuG7SkeWhEbzgjApVdrMMvd6U=,tag:Wk3sYLWtrpkpgDPFD/8sWw==,type:str]
    SVC_VECTOR_ADDR: ENC[AES256_GCM,data:JaOy6Tk4m/gA0Y8+Yyc=,iv:3b+l/VBL5mz7/6EE23HiKFam1D7B/3fkOiediZvJEWg=,tag:5QS5pqETqy7BN86DPsdJNQ==,type:str]
    SVC_CPGO_ADDR: ENC[AES256_GCM,data:Kc3ByEZx3NMD1PLQhR0=,iv:WekzGI99sUH9Kmgh5VPdHZFD7w+/wQQdXzEIoWcCIVM=,tag:1si0I31NICYmysOEsdrBxw==,type:str]
    SVC_ISTIO_ADDR: ENC[AES256_GCM,data:YX1HDDV5cjotPrLjqtc=,iv:f8oNaM6OmtDpZTcJHO4IoAIXOLUUNqlVCNtD2wHlkkw=,tag:UFaNycocvCDdVR0H7uY26Q==,type:str]
    SVC_GATEWAY_ADDR: ENC[AES256_GCM,data:xfGpYpuof5Q5r9dmDog=,iv:c+qVNGqzZdPZ9eO0e5qIPmpAu0mWgZeX0B63Jx/iM1o=,tag:0huFkc5de6hR/peJbL/FyQ==,type:str]
    SVC_HARBOR_ADDR: ENC[AES256_GCM,data:2lEq6GLh8cgrFZ+AsdM=,iv:MEoVMEool6+8QRSCb7ijWyQ9ERh5QASH+XZ9fsn0R1g=,tag:aVI3U0FR1QPP0aFQQ5JFug==,type:str]
    SVC_TAILSCALE_ADDR: ENC[AES256_GCM,data:Rdcb6g4dN5z2+hZXDFY=,iv:p+95qmc93mq3VRxbDbbh+EZBtZFMdmzGfkKfY+39SZ8=,tag:JygIhCAFlzruQLsudSaZJQ==,type:str]
    SVC_SPARK_ADDR: ENC[AES256_GCM,data:0+k8NIm1hhB+5IOdDKo=,iv:UXK6gdt3x7UzTqyvTb/vxQuYkAysOO3VFMkowoqrHCc=,tag:+Qj5rBEs8v/YzywRxRKOFw==,type:str]
    SVC_PTERODACTYL_WINGS_ADDR: ENC[AES256_GCM,data:9Z3pbj9ugc0ynE66EmE=,iv:BwIVwi4epPnMT+fKJwdu+lRhnDRKVqsK2cF5K8iZQYY=,tag:Ymb1qNqSgzm8U18AjLzrOQ==,type:str]
    SECRET_NFS_DATA: ENC[AES256_GCM,data:UUDaz6JSfbPZ,iv:cTdQtNhINPo4FVniHifxnVNkAs205YWRSYnDXQeoTl8=,tag:uWHb6Ex2QYLCe2ScQzEtKw==,type:str]
    SECRET_NFS_PPM: ENC[AES256_GCM,data:0Qo/57fGSEGGOAJ6AIHIJuOMzfSKtgxIWWc=,iv:noE4WvT0vmSqPeSv+1uGAOjrzdiGi6VadjdTrONerf8=,tag:X4lUvdxk2+FoxzeX5lL97g==,type:str]
    SECRET_NFS_WATCHER: ENC[AES256_GCM,data:iLjyD7/OJQ1RHruSpSA88sSds2Ejzde/IUHg,iv:JD4HdD/l4LVWk+MW7IJKYDUWNHL/ca+uIEfnLpPa9MM=,tag:1bSJQ5UikbO4kAHKVRrNtg==,type:str]
    SECRET_NFS_MUSIC: ENC[AES256_GCM,data:JTgZO9A6coU/HRY3E4RN,iv:eJc4mALOoMoPMmGdtyrqGP4dc3mC8AQYQkYAVxvtLC8=,tag:Ska2JgnqUiyQ0nYhhwh/ZQ==,type:str]
    SECRET_NFS_POSTGRES: ENC[AES256_GCM,data:EMqH3xzz6/RLgKkZ3OOpcKmXi/9e6Kzy6r4D,iv:1h9yL1+eFuWvNk2D7RkewTbNEH9x74BHdavOlZmvNIY=,tag:DKz8MT8lw+bN2cMa81VkAA==,type:str]
    SECRET_NFS_SYNCTHING: ENC[AES256_GCM,data:CBUwllizhDAFVxs/ReNlYdtMog==,iv:gTjawKADqyOJdVXx9v8jZthawd3lQuuuMvPbYiLYwY4=,tag:7SyBRhyD5WT3iqvEWW9FwQ==,type:str]
    SECRET_NFS_PAPERLESS: ENC[AES256_GCM,data:FeXxZYBchgM8op/JvobgBGLcBw==,iv:m0HAb3wNO8IVCUJ4taczHhQXl4s8C0WNRa+Ed7mOGZI=,tag:oQsAxI92yK4I5INS3wAVUg==,type:str]
    MINIO_TOKEN: ENC[AES256_GCM,data:2AUjjpK+secgBr9QsizE2YNCDBk=,iv:ikFzyr+2AsJKOEgBdvRyeHzv2BkFGfcyi+H/ZNm1k0c=,tag:7vOStcCbHdyovOtxKo1GDw==,type:str]
    NAS_IP: ENC[AES256_GCM,data:Vre+bU9tG7mDQwRYYw==,iv:yF2Lyoa0HzJ4BX8k2sywfbQ2r175KsFcYkzxlWai6t8=,tag:UG7xyxaAcmQyRTPXikr3CQ==,type:str]
    SUPERMICRO_IP: ENC[AES256_GCM,data:b/sGgrJEIhTqkdZRpQ==,iv:hGB0X7jF0TTXP3fF7ziGSAJBwqjK3FfxaVVqehxuojs=,tag:V96eqPfoQZgWvkOPF07ndA==,type:str]
    UNIFI_CONTROLLER_IP: ENC[AES256_GCM,data:rlgCpxPxCqegXBZO1Hr0dDBjGw==,iv:/7hZ0owwBtKwn3WG4Q2pHiXNu4rsyKlDypbpjBojydc=,tag:bSLyMcAbSVMtw/or/dZIIg==,type:str]
    PLEX_TOKEN: ENC[AES256_GCM,data:v/8+T1JX0lVOTm03Zx/t4mFui54=,iv:lBMg0MMisij/xmlb7GYjneWql3Ec459QYv1b44GgLsc=,tag:H8M5aWVYmpsOEguDBIwymg==,type:str]
    LATITUDE: ENC[AES256_GCM,data:e8C/C5IAt67cMpxgHizjj+s=,iv:aG0kUNKd0ij+edRi2D1yz7HH94wHaJHTOplk17sNHHc=,tag:pF9D2nn3GaszOcoBIY1P7g==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:f/6zfSFqpHwtsrMVQKMvrA8d,iv:IqbtYmyMgdJpxVtn+ffFgAGmHfVDZJvx0K9JoMtBolY=,tag:bwi1kexCnT/WHwIUT9RfLw==,type:str]
    #ENC[AES256_GCM,data:bGAiVKLU8DF2jBSfNBSGKmWM7jKGj7M=,iv:Y5gbSYHcAQttIlC7mwzouo2T0+XGlBe4JrWecjMM3aI=,tag:43Fz3rx4NKakM0cx3Zfo1Q==,type:comment]
sops:
    age:
        - recipient: age15wktkwh8dgasswz9u04axxaa4edc88nld3ajldnr3mtgjfmfyqtqc0cu0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TmRHaDZBVmErQWVWdzlK
            M0pKSDNjeVBpV1I3WVdWK1VIZ2g5WXpsdG5VCkE1Qkg1bWFoQ1RxUUYvOHMzV2ox
            TVdTMUJxZWwrY1R3VHRYbFdUcTJIcnMKLS0tIDBpN1NaYUF2WEViN085QmVHTk5G
            N3Z6YTBjbTZrQktzVlFnTEtrazIzRmsKI2VqnQSRFU+rwtxJwb6BENfleATAeMgS
            W5UJAcc8u40kRxp/kCtoj1KSC7+oqfuFkX486CiTc25SawOCRji4qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T14:37:10Z"
    mac: ENC[AES256_GCM,data:tsLr9VC3CTk+xN9dl3t3YJaEPDYLhNK4GvRIEj/swZM3wlJHjsY8VkgdzFUJyp3ADECi1a1xXiFV+E4EMlZCZ1yQ9AUTDiIvwz+TXX1yAy+kExd4UbaEFRcC0Z5o68+etzRJZ/tMNWkNx7+CbR8V7oOJfDe/H2mzohgEN8gsQBI=,iv:vmYIyLXiJurRp8ULzh47nx/kBbWUgNXdYdw1G6J3cso=,tag:CT7AioAHVSz4Kaxk2GFO7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
