apiVersion: v1
kind: Pod
metadata:
  name: mlflow-db-upgrade
  namespace: datasci
spec:
  containers:
  - name: mlflow
    image: ghcr.io/ninerealmlabs/mlflow-server:3.15.1@sha256:d73a3121751cc4a22fe9b1e614a63075c473ebcb3cf6aea42d840d3c6ea6c6ca
    command: ["sleep", "3600"]  # This will keep the pod running for an hour
    env:
    - name: MLFLOW_BACKEND_STORE_URI
      valueFrom:
        secretKeyRef:
          name: mlflow-secret
          key: MLFLOW_BACKEND_STORE_URI
  restartPolicy: Never
