apiVersion: v1
kind: Pod
metadata:
  name: mlflow-db-upgrade
  namespace: datasci
spec:
  containers:
  - name: mlflow
    image: ghcr.io/ninerealmlabs/mlflow-server:3.12.0@sha256:0eefff9476607a4622d9833d6c4c6d70b0ce249af62e55ac6f329dc1337674dc
    command: ["sleep", "3600"]  # This will keep the pod running for an hour
    env:
    - name: MLFLOW_BACKEND_STORE_URI
      valueFrom:
        secretKeyRef:
          name: mlflow-secret
          key: MLFLOW_BACKEND_STORE_URI
  restartPolicy: Never
