apiVersion: v1
kind: Pod
metadata:
  name: mlflow-db-upgrade
  namespace: datasci
spec:
  containers:
  - name: mlflow
    image: ghcr.io/ninerealmlabs/mlflow-server:3.14.0@sha256:dd7b0d1492531d00ec0b6f41c1b4a0418142bc25cbb86d65a84d8d579623ddd9
    command: ["sleep", "3600"]  # This will keep the pod running for an hour
    env:
    - name: MLFLOW_BACKEND_STORE_URI
      valueFrom:
        secretKeyRef:
          name: mlflow-secret
          key: MLFLOW_BACKEND_STORE_URI
  restartPolicy: Never
