{
 "title": "Ray Subsystem Health",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(ray_node_network_receive_speed{}, ray_io_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Core Active Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(ray_node_cpu_count{ray_io_cluster=~\"$Cluster\"}) > 0"
    }
   ]
  },
  {
   "title": "Data Metrics Present",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "count({__name__=~\"ray_data_.*\",ray_io_cluster=~\"$Cluster\"}) > 0"
    }
   ]
  },
  {
   "title": "Train Metrics Present",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count({__name__=~\"ray_train_.*\",ray_io_cluster=~\"$Cluster\"}) > 0"
    }
   ]
  },
  {
   "title": "Tune Metrics Present",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count({__name__=~\"ray_tune_.*\",ray_io_cluster=~\"$Cluster\"}) > 0"
    }
   ]
  },
  {
   "title": "Serve Metrics Present",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "count({__name__=~\"ray_serve_.*\",ray_io_cluster=~\"$Cluster\"}) > 0"
    }
   ]
  },
  {
   "title": "RLlib Metrics Present",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "count({__name__=~\"ray_rllib_.*|rllib_.*\",ray_io_cluster=~\"$Cluster\"}) > 0"
    }
   ]
  }
 ]
}