---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${job}
  namespace: default
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      nodeName: ${node}
      containers:
        - name: main
          image: alpine:latest@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache sgdisk util-linux util-linux-misc parted device-mapper;
              sgdisk --zap-all ${disk};
              dd if=/dev/zero of=${disk} bs=1M count=100 oflag=direct;
              dd if=/dev/zero of=${disk} bs=1M count=100 oflag=direct;
              blkdiscard ${disk};
              partprobe ${disk};
          securityContext:
            privileged: true
          resources: {}
