---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${job}
  namespace: default
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      nodeName: ${node}
      containers:
        - name: main
          image: alpine:latest@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
          command: ["/bin/sh", "-c"]
          args: ["rm -rf /mnt/host_var/lib/rook"]
          volumeMounts:
            - mountPath: /mnt/host_var
              name: host-var
          securityContext:
            privileged: true
          resources: {}
      volumes:
        - name: host-var
          hostPath:
            path: /var
