---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app suggestarr
spec:
  interval: 1h
  maxHistory: 1
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  - name: volsync
    namespace: storage
  values:
    controllers:
      *app :
        type: statefulset
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            runAsNonRoot: true
            seccompProfile: { type: RuntimeDefault }
            fsGroupChangePolicy: Always
        containers:
          main:
            image:
              repository: docker.io/ciuse99/suggestarr
              tag: "v2.4.3"
            env:
              SUGGESTARR_PORT: &port 5000
              LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: ${APP}-secret
            securityContext:
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
              allowPrivilegeEscalation: false
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 50m
                memory: 128Mi
            probes:
              liveness:
                enabled: true
                type: HTTP
              readiness:
                enabled: true
                type: HTTP
    service:
      main:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: SuggestArr
          gethomepage.dev/icon: suggestarr.png
          gethomepage.dev/description: SuggestArr - request recommended movies and TV shows to Jellyseer/Overseerr from Jellyfin/Plex/Emby watch history
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        hosts:
        - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              identifier: main
              port: http
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/config/config_files
