---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./model-arm-0.yaml
  - ./model-arm-1.yaml
  - ./experiment-bandit.yaml
