---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./admin.yaml
  - ./alert-triage.yaml
  - ./pr-review.yaml
  - ./openclaw.yaml
  - ./toolhive.yaml
  - ./opencode.yaml
  - ./atlas.yaml
  - ./agent-lab.yaml
